### ISSUE TITLE
Running the make file in windows. last step in this installation

### ISSUE THREAD

**Issue by sadiq7753** [washingtonpost/datawrapper#13]
I have followed all the installation steps exactly But i cant run the make file. im using windows 8.1 and MAMP is installed. I tried installing make that is giving this error "nothing to be done for make"

**Comment by sadiq7753** [comment]
this error in the browser. when i load localhost
Slim Application Error
The application could not run because of the following error:

Details

Code: 8
Message: Undefined offset: 0
File: C:\MAMP\htdocs\datawrapper\lib\utils\add_header_vars.php
Line: 223
Trace

#0 C:\MAMP\htdocs\datawrapper\lib\utils\add_header_vars.php(223): Slim::handleErrors(8, 'Undefined offse...', 'C:\MAMP\htdocs\...', 223, Array)
#1 C:\MAMP\htdocs\datawrapper\controller\home.php(20): add_header_vars(Array, '')
#2 [internal function]: {closure}()
#3 C:\MAMP\htdocs\datawrapper\vendor\Slim\Route.php(395): call_user_func_array(Object(Closure), Array)
#4 C:\MAMP\htdocs\datawrapper\vendor\Slim\Slim.php(1145): Slim_Route->dispatch()
#5 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\Flash.php(84): Slim->call()
#6 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\MethodOverride.php(91): Slim_Middleware_Flash->call()
#7 C:\MAMP\htdocs\datawrapper\vendor\Slim\Middleware\PrettyExceptions.php(65): Slim_Middleware_MethodOverride->call()
#8 C:\MAMP\htdocs\datawrapper\vendor\Slim\Slim.php(1097): Slim_Middleware_PrettyExceptions->call()
#9 C:\MAMP\htdocs\datawrapper\www\index.php(94): Slim->run()
#10 {main}
